# Setup environment
version: '0.0.{build}'

nuget:
  disable_publish_on_pr: true

pull_requests:
  do_not_increment_build_number: true

branches:
  except:
    - /tmp|temp/

skip_commits:
  files:
  - .github/
  - .gitattributes
  - .gitignore
  - LICENSE
  - README.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - CODE_OF_CONDUCT.md
  - '**/*.DotSettings'

environment:
  NUGET_API_KEY:
    secure: zq0+IBIITvBHIsVd7MmRQl09X2q4erMzK7LBi2UTpjNFgJeY/R+Krm4dZWAcb4E1
  GITHUB_ACCESS_TOKEN:
    secure: w8H/kYnxC0NVBLhm4uXSLNH110FtIAQ1COq0Wl5RgwDCG3apzXfSCEfJcwSc44QQ
  GITHUB_EMAIL:
    secure: CxOftS/5wmEkPCDl0O/KIiKlF4KhUnGD9436K/1iQwY3RkDMZRCkCEny+dG5zCS+
  FORCE_DOC_PUSH: true

image:
  - Ubuntu
  - Visual Studio 2019

# Setup build version
install:
  - ps: ./build/setup-build.ps1

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(Build_Assembly_Version)'
  package_version: '$(Build_Version)'
  assembly_version: '$(Build_Assembly_Version)'
  file_version: '$(Build_Assembly_Version)'
  informational_version: '$(Build_Version)'

# Build configurations
platform:
  - Any CPU

configuration:
  - Release

matrix:
  fast_finish: true

# Build
build:
  verbosity: minimal

build_script:
  - dotnet build

test_script:
  - ps: ./build/run-tests.ps1

artifacts:
  - path: '**\bin\Release\*.nupkg'
    name: NuGet
  - path: '**\bin\Release\*.snupkg'
    name: NuGet symbols

for:
  - matrix:
      only:
        - image: Visual Studio 2019
    before_deploy:
      # Release documentation
      - ps: ./build/publish-docs.ps1
    deploy:
      ## GitHub
      - provider: GitHub
        auth_token:
          secure: 53MNc4RNkaB8Cj54MNxuyLf9syy+i54ITECxm7HhmbJZfIJvzIss6WbiHZ4mCXAW
        release: '${APPVEYOR_REPO_TAG_NAME}'
        description: 'Version ${Release_Name}'
        draft: false
        prerelease: false
        force_update: true
        on:
          configuration: Release
          APPVEYOR_REPO_TAG: true
      # NuGet
      - provider: NuGet
        api_key:
          secure: zq0+IBIITvBHIsVd7MmRQl09X2q4erMzK7LBi2UTpjNFgJeY/R+Krm4dZWAcb4E1
        on:
          configuration: Release
          APPVEYOR_REPO_TAG: true

