//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Firefly Consulting Ltd.")]
[assembly: AssemblyProduct("Firefly.CrossPlatformZip")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyCopyright("Copyright © Firefly Consulting Ltd. 2019")]
[assembly: AssemblyConfiguration("Release")]
[assembly: ComVisible(false)]

